spring:
  application:
    name: announcement-service

  datasource:
    url: jdbc:postgresql://localhost:5433/db-announcement
    username: postgres
    password: postgres

    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8084

feign:
  httpclient:
    hc5:
      enabled: true
  client:
    config:
      default:
        loggerLevel: FULL

logging:
  level:
    feign: DEBUG
    hello.pet.announcementservice.client: DEBUG
    hello.pet.announcementservice.facade: DEBUG
