spring:
  application:
    name: announcement-service

  datasource:
    url: jdbc:postgresql://localhost:5432/db-announcement
    username: postgres
    password: postgres

    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8084
